### ISSUE TITLE
Trying to build 2nd wood farm

### ISSUE THREAD

**Issue by nftbulbhead** [BibliothecaDAO/eternum#1027]
Got all the resources and population available but the tx to set another wood-production doesn't go through

Err:
Failed to place building: j2: RPC: starknet_estimateFee with params {
  "request": [
    {
      "type": "INVOKE",
      "sender_address": "0xc2af222980d105f056659f8b44041c8285c3fb7ed8796623c7396cce7d2a59",
      "calldata": [
        "0x1",
        "0x4206c85fe040ba0874e151851ee7ec55952fa59708cddda324e84fe6f7057ef",
        "0xa69ce1f5effb50e2d3ea666665dfbac26c73d9403c4adaa22c222bb1c8d92b",
        "0x6",
        "0x517",
        "0xb",
        "0xa",
        "0x2",
        "0x0",
        "0x1"
      ],
      "version": "0x100000000000000000000000000000001",
      "signature": [],
      "nonce": "0x22",
      "max_fee": "0x0"
    }
  ],
  "block_id": "pending",
  "simulation_flags": [
    "SKIP_VALIDATE"
  ]
}
 
        41: Transaction execution error: {"execution_error":"transaction reverted: Error in the called contract (0x00c2af222980d105f056659f8b44041c8285c3fb7ed8796623c7396cce7d2a59):\nError at pc=0:4573:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:67)\nUnknown location (pc=0:1835)\nUnknown location (pc=0:2478)\nUnknown location (pc=0:3255)\nUnknown location (pc=0:3795)\n\nError in the called contract (0x04206c85fe040ba0874e151851ee7ec55952fa59708cddda324e84fe6f7057ef):\nError at pc=0:12392:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:22955)\nUnknown location (pc=0:22880)\nUnknown location (pc=0:16004)\nUnknown location (pc=0:25360)\nUnknown location (pc=0:31709)\nUnknown location (pc=0:21500)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28493)\nUnknown location (pc=0:28396)\nUnknown location (pc=0:15321)\nUnknown location (pc=0:24005)\nUnknown location (pc=0:17583)\n\nError in the called contract (0x005f05e3e3ca9deb6552d9037f48e8f0faf03c394c8014ad0884d9c5231b75ec):\nError at pc=0:15236:\nCould not reach the end of the program. RunResources has no remaining steps.\nCairo traceback (most recent call last):\nUnknown location (pc=0:3809)\nUnknown location (pc=0:9686)\nUnknown location (pc=0:15343)\nUnknown location (pc=0:9572)\n","transaction_index":0}
    at tde.errorHandler (https://alpha-eternum.realms.world/assets/vendor-CiNf1F6c.js:4481:10711)
    at tde.fetchEndpoint (https://alpha-eternum.realms.world/assets/vendor-CiNf1F6c.js:4483:210)
    at async IE.getSuggestedFee (https://alpha-eternum.realms.world/assets/vendor-CiNf1F6c.js:4483:40260)
    at async IE.getUniversalSuggestedFee (https://alpha-eternum.realms.world/assets/vendor-CiNf1F6c.js:4483:40082)
    at async IE.execute (https://alpha-eternum.realms.world/assets/vendor-CiNf1F6c.js:4483:36749)
    at async v0.execute (https://alpha-eternum.realms.world/assets/vendor-CiNf1F6c.js:4483:109458)
    at async v0.executeAndCheckTransaction (https://alpha-eternum.realms.world/assets/main-CI-Dy0h4.js:1:25628)
    at async j (https://alpha-eternum.realms.world/assets/main-CI-Dy0h4.js:46:79830)
    at async placeBuilding (https://alpha-eternum.realms.world/assets/main-CI-Dy0h4.js:44:989)
    at async l (https://alpha-eternum.realms.world/assets/main-CI-Dy0h4.js:44:1843)

<img width="1169" alt="Screenshot 2024-06-26 at 23 28 45" src="https://github.com/BibliothecaDAO/eternum/assets/102306479/b5f4c60e-eb24-4e9d-b1a5-78bca8e1d3e5">

**Comment by ponderingdemocritus** [comment]
I think i know the issue. You will have to wait until the purge tomorrow.
