### ISSUE TITLE
[contracts] u128_sub Overflow

### ISSUE THREAD

**Issue by edisontim** [BibliothecaDAO/eternum#1902]
This happened after multiple successive pillages on the same structure, adding troops to either armies didn't fix it
<img width="1708" alt="Screenshot 2024-10-23 at 18 31 02" src="https://github.com/user-attachments/assets/a415711e-afe1-4683-a225-14e2daea97b3">

```
BattleActions.tsx:116 Error during pillage: Error: Transaction failed with reason: Transaction execution has failed:
0: Error in the called contract (contract address: 0x016f8a351add7ceaa26841c00633177dd16c3f49e043c4af96fae03cb62b2058, class hash: 0x07dc7899aa655b0aae51eadff6d801a58e97dd99cf4666ee59e704249e51adf2, selector: 0x015d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad):
Error at pc=0:4211:
Cairo traceback (most recent call last):
Unknown location (pc=0:290)
Unknown location (pc=0:2951)

1: Error in the called contract (contract address: 0x06bde5ad6204af5e31e9b66f687f5ccd84fcefa1b61dfba9bda8ca331252e641, class hash: 0x074259da93bd2cd6b8a13844a7df752501717e9ad7a514ad57da5535eeb84a86, selector: 0x018f505bd039d3fbc20655d8359bcda825bd8fac64a17ead4b26d26917199428):
Execution failed. Failure reason: 0x753132385f737562204f766572666c6f77 ('u128_sub Overflow').

    at ne.waitForTransactionWithCheck (index.ts:72:56)
    at async ne.executeAndCheckTransaction (index.ts:58:27)
    at async ne.battle_pillage (index.ts:551:16)
    at async battle_pillage (createSystemCalls.ts:303:5)
    at async createSystemCalls.ts:68:16
    at async createSystemCalls.ts:61:53
    at async createSystemCalls.ts:13:26
    at async PromiseQueue.processQueue (createSystemCalls.ts:31:11)
overrideMethod @ hook.js:608
handleRaid @ BattleActions.tsx:116
await in handleRaid
onClick @ Button.tsx:58
callCallback2 @ chunk-FEIN2JPW.js?v=f6656c57:3674
invokeGuardedCallbackDev @ chunk-FEIN2JPW.js?v=f6656c57:3699
invokeGuardedCallback @ chunk-FEIN2JPW.js?v=f6656c57:3733
invokeGuardedCallbackAndCatchFirstError @ chunk-FEIN2JPW.js?v=f6656c57:3736
executeDispatch @ chunk-FEIN2JPW.js?v=f6656c57:7014
processDispatchQueueItemsInOrder @ chunk-FEIN2JPW.js?v=f6656c57:7034
processDispatchQueue @ chunk-FEIN2JPW.js?v=f6656c57:7043
dispatchEventsForPlugins @ chunk-FEIN2JPW.js?v=f6656c57:7051
(anonymous) @ chunk-FEIN2JPW.js?v=f6656c57:7174
batchedUpdates$1 @ chunk-FEIN2JPW.js?v=f6656c57:18913
batchedUpdates @ chunk-FEIN2JPW.js?v=f6656c57:3579
dispatchEventForPluginEventSystem @ chunk-FEIN2JPW.js?v=f6656c57:7173
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ chunk-FEIN2JPW.js?v=f6656c57:5478
dispatchEvent @ chunk-FEIN2JPW.js?v=f6656c57:5472
dispatchDiscreteEvent @ chunk-FEIN2JPW.js?v=f6656c57:5449
Show 16 more frames
Show less
```

**Comment by edisontim** [comment]
Attacking with a different army solved the issue though

**Comment by ponderingdemocritus** [comment]
@credence0x could this be due to the decimals?
