### ISSUE TITLE
Settling Realm doesn't work

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaDAO/eternum#37]
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/42129905-9d7f-40c2-aabb-34fee70e79c5)

Just get a loading spinner, that's all.

Here are the errors in my console, just in case it is relevant:
```
Uncaught (in promise) Object
index-1decbfba.js:5634 Uncaught (in promise) eb: 25: Transaction hash not found
    at FP.errorHandler (https://alpha-eternum.realms.world/assets/index-1decbfba.js:5634:132151)
    at FP.fetchEndpoint (https://alpha-eternum.realms.world/assets/index-1decbfba.js:5634:132284)
    at async create_realm (https://alpha-eternum.realms.world/assets/index-1decbfba.js:5645:332803)
    at async n (https://alpha-eternum.realms.world/assets/index-1decbfba.js:5623:10707)
DevTools failed to load source map: Could not load content for chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/inject.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/inpage.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by Amaro-Koberle** [comment]
sweet! thanks
