### ISSUE TITLE
not able to accept 'deposit resources' on FragmentMine

### ISSUE THREAD

**Issue by nftbulbhead** [BibliothecaDAO/eternum#989]
I tried to send 400 donkey to my shardMine but I can't accept them there.

console output:
Uncaught (in promise) j2: RPC: starknet_estimateFee with params {
  "request": [
    {
      "type": "INVOKE",
      "sender_address": "0x479cb5e527510f3707d9bd347ff60939aae284fa4f848962c8cbff7a4c78985",
      "calldata": [
        "0x1",
        "0x45bcbc495cb2398deaa0dd3000b8e69b42e3c010aa3bc4b50cddded6ef7bce1",
        "0x38fb7b2e3c9c2e712beb3f0810da51cfd22c24f931002cf7b8fe9ec042de50c",
        "0x5",
        "0x270",
        "0x26f",
        "0x1",
        "0xf9",
        "0x61a80"
      ],
      "version": "0x100000000000000000000000000000001",
      "signature": [],
      "nonce": "0x17d",
      "max_fee": "0x0"
    }
  ],
  "block_id": "pending",
  "simulation_flags": [
    "SKIP_VALIDATE"
  ]
}
 
        41: Transaction execution error: {"execution_error":"transaction reverted: Error in the called contract (0x0479cb5e527510f3707d9bd347ff60939aae284fa4f848962c8cbff7a4c78985):\nError at pc=0:4573:\nGot an exception while executing a hint: Execution failed. Failure reason: \"resource locked for entity 623\".\nCairo traceback (most recent call last):\nUnknown location (pc=0:67)\nUnknown location (pc=0:1835)\nUnknown location (pc=0:2478)\nUnknown location (pc=0:3255)\nUnknown location (pc=0:3795)\n\nError in the called contract (0x045bcbc495cb2398deaa0dd3000b8e69b42e3c010aa3bc4b50cddded6ef7bce1):\nExecution failed. Failure reason: \"resource locked for entity 623\".\n","transaction_index":0}
    at ede.errorHandler (https://alpha-eternum.realms.world/assets/vendor-Dv4TNuN2.js:4481:10711)
    at ede.fetchEndpoint (https://alpha-eternum.realms.world/assets/vendor-Dv4TNuN2.js:4483:210)
    at async RE.getSuggestedFee (https://alpha-eternum.realms.world/assets/vendor-Dv4TNuN2.js:4483:40260)
    at async RE.getUniversalSuggestedFee (https://alpha-eternum.realms.world/assets/vendor-Dv4TNuN2.js:4483:40082)
    at async RE.execute (https://alpha-eternum.realms.world/assets/vendor-Dv4TNuN2.js:4483:36749)
    at async _0.execute (https://alpha-eternum.realms.world/assets/vendor-Dv4TNuN2.js:4483:109458)
    at async _0.executeAndCheckTransaction (https://alpha-eternum.realms.world/assets/main-DJQW3Rbk.js:1:25629)
    at async _0.send_resources (https://alpha-eternum.realms.world/assets/main-DJQW3Rbk.js:1:28417)
    at async Object.send_resources (https://alpha-eternum.realms.world/assets/main-DJQW3Rbk.js:46:49554)
    at async u (https://alpha-eternum.realms.world/assets/main-DJQW3Rbk.js:16:25705)

**Comment by nftbulbhead** [comment]
<img width="1440" alt="Screenshot 2024-06-23 at 15 34 07" src="https://github.com/BibliothecaDAO/eternum/assets/102306479/7333b0f6-172f-4bc0-b120-7f4efac156ac">

**Comment by aymericdelab** [comment]
thanks for creating the issue !  we'll look into it

**Comment by ponderingdemocritus** [comment]
is this still happening @nftbulbhead

**Comment by nftbulbhead** [comment]
<img width="1267" alt="Screenshot 2024-06-26 at 23 15 58" src="https://github.com/BibliothecaDAO/eternum/assets/102306479/2121ecfe-6127-4169-8797-13c3553e16fa">


> is this still happening @nftbulbhead

Yes

**Comment by nftbulbhead** [comment]
no battle happening there^^

**Comment by edisontim** [comment]
Will close this, fixed in #1089
